### PR TITLE
Make window.location.href available in privacypolicy.html

### PR DESCRIPTION
**Pull request by randnetdd**
setPrivacyPolicyURL() is provided, but If you perform a task kill, the app's permissions page will read privacypolicy.html  
If you want to put a privacy policy on a web page, you must specify the URL using Javascript.  

window.location.href = 'https://www.google.com/';

### CODE REVIEW

**Comment by dariosalvi78** [comment]
I don't get it, why do we need this?

**Comment by randnetdd** [comment]
On Android 14, when connecting to Health Connect, 🛈 will be added to the app's permissions screen. 
Tapping this icon will open the URL set as your privacy policy. 
Screenshot

When you exit the app, the value set with setPrivacyPolicyURL will be initialized to privacypolicy.html 
Therefore, if you want to specify a privacy policy on a web page, you need to redirect it using the privacypolicy.html file. 
Webview cannot use Javascript due to a security error unless WebSettings is set, so this is the setting for that purpose. 
 
Task kill is to terminate running apps from Android's task manager. 
https://www.au.com/support/faq/detail/19/a00000000919/ 
https://www.android.com/intl/ja_jp/articles/55/ 
Japanese page

**Comment by dariosalvi78** [comment]
ok, now I see. It's a use case I was not aware of. I could reproduce it also on Android <14 actually.

So it turns out that the Privacy Policy can be called also from within HealthConnect, that is independently from the execution of the app. 

In all honesty, I think that this requires changing the way the html page is specified, your proposal is kind of hackish. I will accept it for now, but I will need to change the way the page is specified in a future version.

**Comment by dariosalvi78** [comment]
@randnetdd  I have removed your change. Now the URL of the Privacy Policy is specified in a XML resource file, which is persistent and can be manually modified.

I suspect that Cordova may decide to overwrite that file when resetting things. To make the change to the resource file permanent, one would need to add an <edit-config> to config.xml, but I haven't managed to make my example work. If someone finds out how to do it please add an example to the README.

**Pull request merged**
