### PR TITLE
Allow the user to set google services version

### PR DESCRIPTION
**Pull request by artonge**
Right now I have the following error:
```shell
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"
```

With this change, a user can now override the used google services version by setting the `GMS_VERSION` in `config.xml`

Inspired from: [cordova-plugin-google-analytics](https://github.com/danwilson/google-analytics-plugin/blob/1bd62ad1a49183bd839dadcacfcea22cf11fe99b/plugin.xml#L55)

### CODE REVIEW

**Comment by dariosalvi78** [comment]
not a bad idea. Could the default be "+" ?

**Comment by artonge** [comment]
Yes of course, but the "+" generate some error for me (see my first message). Maybe I am missing something...

**Comment by artonge** [comment]
Some news: it seems like from version 15 it is not necessary to have the same play services / firebase versions across plugins: https://developers.google.com/android/guides/versioning

It think this plugin should, by default, use the google services version it has been tested with, and still allow  the user to set a custom version with my proposal.

**Comment by dariosalvi78** [comment]
thanks for your input, very much appreciated.
Yes, if you can confirm that version 16.0.1 works, then I'd default it to that.

At the moment I can't develop very much, so I won't be able to test it myself, but I'll trust the work you've done and merge your PR as soon as we agree on what to use as default.

**Comment by dariosalvi78** [comment]
shouldn't `<preference name="GMS_VERSION" default="11.0.1"/>` in plugin.xml be updated to 16.0.1 too?

**Pull request merged**
