### PR TITLE
added new type activitydistcal to support distance and calories for android devices

### PR DESCRIPTION
**Pull request by petemcwilliams**
related to issues #41, #47, and #82

Added new type to keep existing functionality of activity unchanged
For queryAggregate we query and aggregate distance and calories over the activity type for the activity bucket start and end times
For query we find distance and calorie records for the start and end date.  These records are listed alongside the activity.

### CODE REVIEW

**Comment by dariosalvi78** [comment]
Thanks for the PR. Why not just using activity directly? The purpose is to have one single interface for HK and GF!

**Comment by petemcwilliams** [comment]
Not sure what the best approach is for this, I was concerned with the extra required permission of distance required for activity data with this change, was looking for a way to switch that off.

**Comment by dariosalvi78** [comment]
I would rather have one "activity" that has it all.

If one doesn't want to ask too many permissions, we could use "workouts", which was introduced to avoid for that purpose. It works only on iOS now, but we could extend it for GF too (although they have a slightly different scope).

How does it sound?
Would you be willing to change the PR ?

**Comment by petemcwilliams** [comment]
I'm willing to change the PR, will go back and look at it, not sure that using workouts is the right thing in that it will have a different meaning over the two environments.

**Comment by petemcwilliams** [comment]
I'd like to just have activity and if we have the distance permission add that into the activity data.

**Comment by dariosalviwork** [comment]
I think we should ask for all permissions for a given data type upfront, as there is no selective way for asking permissions at a different moment, so if "activity" requires distance, then we need distance.

Regarding the use of workouts: the main difference between HK workouts and GF activity_segment is that GF includes also sleep and biking/in_vehicle (which are detected separately in iOS).

My proposal is that "activity" offers every type of available activity, like in GF, and "workout" could just focus on sport (we can rename it as "sport_activity" if it sounds better).
In that case, in GF, "workout" would map to activity_segment, but filtering out a few cases (sleep and in_vehicle that I can think of). We can also forget the filtering ATM, as it's a bit of a compromise anyway.

BTW, there's also a new "WorkoutExercises" data type in GF, but it's more detailed than HK and related to gym (see #78). In the future we could add those too to "workout".

Would this approach suit your needs?

**Comment by petemcwilliams** [comment]
I've made changes to remove the new type, and now if a developer asks for activity permission it will include request for access to location data also.  I'd like to test it some more so will update the PR tomorrow.

I like the sound of having a "sport_activity" type to include only specific activities but feel that is a different issue, I'm not going to look at that ;)

**Comment by dariosalviwork** [comment]
this is great, thanks! I'll make a release today.

**Comment by FPeters84** [comment]
Many thanks to both of you for this awesome work!!

@petemcwilliams 
Just a small question: it seems like the newly added 'calories' and 'distance' are only returned if a bucket is defined in the query. Not sure if this is an issue or maybe a choice to do it this way?

Kind regards,
Frank

**Comment by petemcwilliams** [comment]
I'm looking to make a change, slipped through my testing I was only interested in bucketed days of data.  Looks like a simple fix.

**Comment by bryantee** [comment]
This for for Android only, correct?

**Comment by petemcwilliams** [comment]
Healthkit was already returning the data when entered as workout.  This PR was to make android behaviour match.

Handy tip... the files changed tab at the top of the page would answer this for you.

**Comment by bryantee** [comment]
Sorry @petemcwilliams, I did notice your changes were only for Android but wasn't sure if this was for feature parity with existing iOS functionality.

**Comment by dariosalviwork** [comment]
I've noticed that there was an inconsistency about how calories and distance were returned in iOS and Android. Basically iOS was returning something like: `calories: 123`, while Android something like: `calories: { startDate:.., endDate:..., value: 123 }`.
Now they both return just the number. This may break your code if you upgrade, so you'd better check it.

**Pull request merged**
