### PR TITLE
Add support for other sleep states introduces with WatchOS 9

### PR DESCRIPTION
**Pull request by mley**
WatchOS 9 now also support core/light, deep and REM sleep. Currently these sleep states are mapped to sleep.awake, which seems not correct.

### CODE REVIEW

**Comment by dariosalvi78** [comment]
thanks

**Comment by mley** [comment]
Thanks for the quick merge. When can we expect an updated version on npmjs.com?

**Comment by dariosalvi78** [comment]
I will publish a new version next week

**Comment by mley** [comment]
Great. Maybe there will be more pull-requests regarding Google Fit, since we need some additional features in our app.

**Pull request merged**
