### PR TITLE
Add systolic, diastolic as separate datatypes

### PR DESCRIPTION
**Pull request by rafaellop**
Due to the fact that the combined `blood_pressure` data type cannot be limited in queries and that there are systolic and diastolic datatypes in the Health API and that they are of the HKSampleQuery type which can be limited, new datatypes has been added.

### CODE REVIEW

**Comment by dariosalvi78** [comment]
I will merge this, thank you for the contribution, although, I would prefer to actually have one data type valid for both Google and iOS.

A simple solution would be to perform two queries in iOS and merge the results by timestamp. Do you think you can do it?
We can discuss the details here in the thread.

**Comment by rafaellop** [comment]
I've been trying to find information regarding `HKCorrelationTypeIdentifier` and limiting the results given but with no success. I'm not comfortable about ObjectiveC.

**Comment by dariosalvi78** [comment]
so the reason why limit does not work with correlation types is because it is not used in the query, see:
https://github.com/dariosalvi78/cordova-plugin-health/blob/fe5a75241185cc8a4b46331b3244ab2ebe93dcef/src/ios/HealthKit.m#L1608

it would be ideal to add the limit parameter to that function, as done in "querySampleType".

Do you think you can try it?

**Comment by dariosalvi78** [comment]
mm, looks like there is no way to limit correlation type queries:

https://developer.apple.com/documentation/healthkit/hkcorrelationquery/1614145-initwithtype?language=objc

**Comment by rafaellop** [comment]
It would be enough to query separately the systolic and diastolic datatypes and combine them into a result like the current blood_pressure returns. For the store function the current solutions works correctly. I can try but not very soon (busy with my app update).

**Pull request merged**
