### PR TITLE
aggregate query added distance and calories when no bucket

### PR DESCRIPTION
**Pull request by petemcwilliams**

### CODE REVIEW

**Comment by dariosalvi78** [comment]
thanks

**Comment by FPeters84** [comment]
Hi @dariosalvi78 ,

Do you have an idea when you will do a new release which includes this fix?
No pressure, just for me to know :)

Thanks in advance!
Frank

**Comment by dariosalviwork** [comment]
done!

**Comment by FPeters84** [comment]
Thanks!

**Pull request merged**
